# Generated by Django 5.0.1 on 2024-02-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="Department",
        ),
        migrations.AddField(
            model_name="master",
            name="Department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="todoApp.department",
            ),
            preserve_default=False,
        ),
    ]
