# Generated by Django 5.0.1 on 2024-03-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoApp", "0002_remove_userprofile_department_master_department"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="DateCompleted",
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
